<?php

session_start();

//check if user is logged in
if (isset($_SESSION['user_id'])) {
    header("Location: home.php");
}

$registrationErr = "";
//check if the registration has failed
if (isset($_SESSION['registration_err'])) {
    if ($_SESSION['registration_err'] == 1) {
        $registrationErr = "Username already exists!";
    } elseif ($_SESSION['registration_err'] == 2) {
        $registrationErr = "Email already exists!";
    }
}

?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup - Secrete</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="resources/style.css">
</head>

<body>
    <!-- main window -->
    <div class="bg">
        <div class="panel">
            <h1>Sign Up</h1>
            <form class="content" onsubmit="return validateRegister()" action="LogRegProcess.php" method="post">
                    <input class="inputfield" name='fname' type="text" id="fullname" placeholder="Full Name" required><br>
                    <input class="inputfield" name='email' type="text" id="email" placeholder="Email" required><br>
                    <input class="inputfield" name='username' type="text" id="username" placeholder="Username" required><br>
                    <input class="inputfield" name='password' type="password" id="password" placeholder="Password" required><br>
                    <input class="inputfield" type="password" id="password2" placeholder="Confirm Password"><br>
                    <p id="err"><?php echo $registrationErr; ?></p>
                    
                    <!-- Empty select tags day, and year will be generated by main.js -->
                    <h3 id="bd">Birth Date</h3>
                    <select name="day" id="dd">    
                    </select>
                    <select name="month" id="mm">
                        <option value="1">January</option>
                        <option value="2">February</option>
                        <option value="3">March</option>
                        <option value="4">April</option>
                        <option value="5">May</option>
                        <option value="6">June</option>
                        <option value="7">July</option>
                        <option value="8">August</option>
                        <option value="9">September</option>
                        <option value="10">October</option>
                        <option value="11">Novemeber</option>
                        <option value="12">December</option>    
                    </select>

                    <select name="year" id="yyyy">
                    </select>

                    <input id="loginbtn" name='register' type="submit" value="Submit">
                    <p>Already a user? <span><a href="index.php">Sign in</a></span></p>
            </form>
        </div>
    </div>
    <!-- Footer -->
    <footer>
        <div>
            <a href="https://github.com/aivantuquero"><i class="bi bi-github"></i></a>
            <a href="https://ph.linkedin.com/in/aivantuquero"><i class="bi bi-linkedin"></i></a>
        </div>
        <p>Made with <span><i style="color:red" class="bi bi-suit-heart-fill"></i></span> by Aivan Carlos Tuquero</p>
    </footer>

    <script type="text/javascript" src="resources/main.js"></script>
</body>

</html>